### ISSUE TITLE
[BUG] Dock Indicators

### ISSUE THREAD

**Issue by JoelPeterPage** [LacertosusRepo/LacertosusRepo.github.io#52]
#### **Information:**
- *Device:* 11 Pro
- *iOS: 13.6.1
- *Tweak: Dock Indicators
- *Package Version:*

#### **Describe the bug:**
Sometimes, the indicator for messages stays on even though no messages..

Respring to clear.

#### **To Reproduce:**
Could be a conflict with;

BadgeMe
FloatingDockPro13
(Contact me for other possible conflicting tweaks)

#### **Expected behavior:**
Indicator to switch off when no new messages 

#### **Screenshots:**

https://imgur.com/a/nS6Uqx9

#### **Additional context**
Add any other context about the problem here. If the issue is causing a crash, please attach the crash report in either a file or Pastebin paste.

**Comment by LacertosusRepo** [comment]
Should be fixed with v1.0.6

**Comment by JoelPeterPage** [comment]
I tested, the issue was still persistent..

I narrowed it down to a conflict with:

sileo://package/com.cpdigitaldarkroom.kairos3.debug

I hope you don’t mind talking with Carlos and working out who should fix?

Thanks champ! Let me know if you need me to do anything! I get on okay with CPDD, probably the designer I would base myself on if I was still in the industry

Sorry, I thought you’d act on me replying to your email...

**Comment by JoelPeterPage** [comment]
I guess I have to open a new issue for you to act on this information?

I don‘t care, be silly.. I know you got notifications from here, I know you saw my email, be a jerk if you must.. I don’t give a care to your bad attitude towards my help!

**Comment by JoelPeterPage** [comment]
Is not closed issue

**Comment by JoelPeterPage** [comment]
> ~Should be fixed with v1.0.6~. Don't have access to Kairos 3 to fix.

Please email tweaks@cpdigitaldarkroom.support

**Comment by JoelPeterPage** [comment]
> > ~Should be fixed with v1.0.6~. Don't have access to Kairos 3 to fix.
> 
> Please email [tweaks@cpdigitaldarkroom.support](mailto:tweaks@cpdigitaldarkroom.support)

I contacted CP... Hopefully he will contact you to help fix this tiny issue..
